server:
  port: 8084
  error:
    include-message: always
local:
  property:
    host:
      ms-bank-account: localhost
      ms-client: localhost
      ms-movement: localhost
      ms-loan: localhost
spring:
  application:
    name: service-credits
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BankCreditsDB
      auto-index-creation: true
  config:
    import: optional:configserver:http://ms-config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      credit:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 3
message:
  demo: leido desde local